/* This file was generated by the Hex-Rays decompiler version 9.1.0.250226.
   Copyright (c) 2007-2021 Hex-Rays <info@hex-rays.com>

   Detected compiler: GNU C++
*/

#include <defs.h>


//-------------------------------------------------------------------------
// Function declarations

__int64 (**init_proc())(void);
__int64 sub_401020(void); // weak
__int64 sub_401030(); // weak
__int64 sub_401040(); // weak
__int64 sub_401050(); // weak
__int64 sub_401060(); // weak
__int64 sub_401070(); // weak
__int64 sub_401080(); // weak
__int64 sub_401090(); // weak
__int64 sub_4010A0(); // weak
// int puts(const char *s);
// void setbuf(FILE *stream, char *buf);
// int printf(const char *format, ...);
// __int64 __fastcall gets(_QWORD); weak
// void *malloc(size_t size);
// __int64 __fastcall __isoc99_scanf(_QWORD, _QWORD); weak
// void __noreturn exit(int status);
void __fastcall __noreturn start(__int64 a1, __int64 a2, void (*a3)(void));
void dl_relocate_static_pie();
void *deregister_tm_clones();
__int64 register_tm_clones(void); // weak
void *_do_global_dtors_aux();
__int64 frame_dummy(); // weak
int menu();
int create_note();
unsigned __int64 read_note();
unsigned __int64 write_note();
int __fastcall main(int argc, const char **argv, const char **envp);
void term_proc();
// int _libc_start_main(int (*main)(int, char **, char **), int argc, char **ubp_av, void (*init)(void), void (*fini)(void), void (*rtld_fini)(void), void *stack_end);
// __int64 _gmon_start__(void); weak

//-------------------------------------------------------------------------
// Data declarations

__int64 (*qword_403FF8)(void) = NULL; // weak
_UNKNOWN edata; // weak
FILE *_bss_start; // idb
FILE *stdin; // idb
FILE *stderr; // idb
char completed_0; // weak
__int64 g_note; // weak


//----- (0000000000401000) ----------------------------------------------------
__int64 (**init_proc())(void)
{
  __int64 (**result)(void); // rax

  result = &_gmon_start__;
  if ( &_gmon_start__ )
    return (__int64 (**)(void))_gmon_start__();
  return result;
}
// 4040E8: using guessed type __int64 _gmon_start__(void);

//----- (0000000000401020) ----------------------------------------------------
__int64 sub_401020()
{
  return qword_403FF8();
}
// 401020: using guessed type __int64 sub_401020();
// 403FF8: using guessed type __int64 (*qword_403FF8)(void);

//----- (0000000000401030) ----------------------------------------------------
__int64 sub_401030()
{
  return sub_401020();
}
// 401020: using guessed type __int64 sub_401020(void);
// 401030: using guessed type __int64 sub_401030();

//----- (0000000000401040) ----------------------------------------------------
__int64 sub_401040()
{
  return sub_401020();
}
// 401020: using guessed type __int64 sub_401020(void);
// 401040: using guessed type __int64 sub_401040();

//----- (0000000000401050) ----------------------------------------------------
__int64 sub_401050()
{
  return sub_401020();
}
// 401020: using guessed type __int64 sub_401020(void);
// 401050: using guessed type __int64 sub_401050();

//----- (0000000000401060) ----------------------------------------------------
__int64 sub_401060()
{
  return sub_401020();
}
// 401020: using guessed type __int64 sub_401020(void);
// 401060: using guessed type __int64 sub_401060();

//----- (0000000000401070) ----------------------------------------------------
__int64 sub_401070()
{
  return sub_401020();
}
// 401020: using guessed type __int64 sub_401020(void);
// 401070: using guessed type __int64 sub_401070();

//----- (0000000000401080) ----------------------------------------------------
__int64 sub_401080()
{
  return sub_401020();
}
// 401020: using guessed type __int64 sub_401020(void);
// 401080: using guessed type __int64 sub_401080();

//----- (0000000000401090) ----------------------------------------------------
__int64 sub_401090()
{
  return sub_401020();
}
// 401020: using guessed type __int64 sub_401020(void);
// 401090: using guessed type __int64 sub_401090();

//----- (00000000004010A0) ----------------------------------------------------
__int64 sub_4010A0()
{
  return sub_401020();
}
// 401020: using guessed type __int64 sub_401020(void);
// 4010A0: using guessed type __int64 sub_4010A0();

//----- (0000000000401130) ----------------------------------------------------
// positive sp value has been detected, the output may be wrong!
void __fastcall __noreturn start(__int64 a1, __int64 a2, void (*a3)(void))
{
  __int64 v3; // rax
  int v4; // esi
  __int64 v5; // [rsp-8h] [rbp-8h] BYREF
  char *retaddr; // [rsp+0h] [rbp+0h] BYREF

  v4 = v5;
  v5 = v3;
  _libc_start_main((int (*)(int, char **, char **))main, v4, &retaddr, 0, 0, a3, &v5);
  __halt();
}
// 40113A: positive sp value 8 has been found
// 401141: variable 'v3' is possibly undefined

//----- (0000000000401160) ----------------------------------------------------
void dl_relocate_static_pie()
{
  ;
}

//----- (0000000000401170) ----------------------------------------------------
void *deregister_tm_clones()
{
  return &edata;
}

//----- (00000000004011A0) ----------------------------------------------------
__int64 register_tm_clones()
{
  return 0;
}
// 4011A0: using guessed type __int64 register_tm_clones();

//----- (00000000004011E0) ----------------------------------------------------
void *_do_global_dtors_aux()
{
  void *result; // rax

  if ( !completed_0 )
  {
    result = deregister_tm_clones();
    completed_0 = 1;
  }
  return result;
}
// 404088: using guessed type char completed_0;

//----- (0000000000401210) ----------------------------------------------------
__int64 frame_dummy()
{
  return register_tm_clones();
}
// 4011A0: using guessed type __int64 register_tm_clones(void);
// 401210: using guessed type __int64 frame_dummy();

//----- (0000000000401216) ----------------------------------------------------
int menu()
{
  puts("1. Create note");
  puts("2. Read note");
  puts("3. Write note");
  puts("4. Exit");
  return printf("> ");
}

//----- (0000000000401271) ----------------------------------------------------
int create_note()
{
  __int64 i; // [rsp+0h] [rbp-10h]
  _QWORD *v2; // [rsp+8h] [rbp-8h]

  if ( g_note )
  {
    for ( i = g_note; *(_QWORD *)(i + 8); i = *(_QWORD *)(i + 8) )
      ;
    v2 = malloc(0x30u);
    *(_DWORD *)v2 = *(_DWORD *)i + 1;
    v2[1] = 0;
    *(_QWORD *)(i + 8) = v2;
    return printf("Note with index %u created\n", *(_DWORD *)v2);
  }
  else
  {
    g_note = (__int64)malloc(0x30u);
    *(_DWORD *)g_note = 0;
    *(_QWORD *)(g_note + 8) = 0;
    return puts("Note with index 0 created");
  }
}
// 404090: using guessed type __int64 g_note;

//----- (0000000000401349) ----------------------------------------------------
unsigned __int64 read_note()
{
  int v1; // [rsp+Ch] [rbp-14h] BYREF
  __int64 i; // [rsp+10h] [rbp-10h]
  unsigned __int64 v3; // [rsp+18h] [rbp-8h]

  v3 = __readfsqword(0x28u);
  if ( g_note )
  {
    v1 = 0;
    printf("Index: ");
    __isoc99_scanf("%u%*c", &v1);
    for ( i = g_note; *(_DWORD *)i != v1; i = *(_QWORD *)(i + 8) )
    {
      if ( !*(_QWORD *)(i + 8) )
        return v3 - __readfsqword(0x28u);
    }
    puts((const char *)(i + 16));
  }
  return v3 - __readfsqword(0x28u);
}
// 401110: using guessed type __int64 __fastcall __isoc99_scanf(_QWORD, _QWORD);
// 404090: using guessed type __int64 g_note;

//----- (0000000000401405) ----------------------------------------------------
unsigned __int64 write_note()
{
  int v1; // [rsp+Ch] [rbp-14h] BYREF
  __int64 i; // [rsp+10h] [rbp-10h]
  unsigned __int64 v3; // [rsp+18h] [rbp-8h]

  v3 = __readfsqword(0x28u);
  if ( g_note )
  {
    v1 = 0;
    printf("Index: ");
    __isoc99_scanf("%u%*c", &v1);
    for ( i = g_note; *(_DWORD *)i != v1; i = *(_QWORD *)(i + 8) )
    {
      if ( !*(_QWORD *)(i + 8) )
        return v3 - __readfsqword(0x28u);
    }
    gets(i + 16);
  }
  return v3 - __readfsqword(0x28u);
}
// 4010F0: using guessed type __int64 __fastcall gets(_QWORD);
// 401110: using guessed type __int64 __fastcall __isoc99_scanf(_QWORD, _QWORD);
// 404090: using guessed type __int64 g_note;

//----- (00000000004014CA) ----------------------------------------------------
int __fastcall __noreturn main(int argc, const char **argv, const char **envp)
{
  int v3; // [rsp+4h] [rbp-Ch] BYREF
  unsigned __int64 v4; // [rsp+8h] [rbp-8h]

  v4 = __readfsqword(0x28u);
  setbuf(stdin, 0);
  setbuf(_bss_start, 0);
  setbuf(stderr, 0);
  while ( 1 )
  {
    menu();
    __isoc99_scanf("%d%*c", &v3);
    if ( v3 == 4 )
      exit(0);
    if ( v3 > 4 )
    {
LABEL_12:
      puts("Wrong choice");
    }
    else
    {
      switch ( v3 )
      {
        case 3:
          write_note();
          break;
        case 1:
          create_note();
          break;
        case 2:
          read_note();
          break;
        default:
          goto LABEL_12;
      }
    }
  }
}
// 40155B: conditional instruction was optimized away because %var_C.4<3
// 401110: using guessed type __int64 __fastcall __isoc99_scanf(_QWORD, _QWORD);
// 401216: using guessed type __int64 menu(void);
// 401271: using guessed type __int64 create_note(void);
// 401349: using guessed type __int64 read_note(void);
// 401405: using guessed type __int64 write_note(void);

//----- (00000000004015AC) ----------------------------------------------------
void term_proc()
{
  ;
}

// nfuncs=40 queued=22 decompiled=22 lumina nreq=0 worse=0 better=0
// ALL OK, 22 function(s) have been successfully decompiled
