/* This file was generated by the Hex-Rays decompiler version 9.1.0.250226.
   Copyright (c) 2007-2021 Hex-Rays <info@hex-rays.com>

   Detected compiler: GNU C++
*/

#include <defs.h>


//-------------------------------------------------------------------------
// Function declarations

__int64 (**init_proc())(void);
__int64 sub_401020(); // weak
// int strncmp(const char *s1, const char *s2, size_t n);
// int puts(const char *s);
// void setbuf(FILE *stream, char *buf);
// int system(const char *command);
// int printf(const char *format, ...);
// ssize_t read(int fd, void *buf, size_t nbytes);
void __fastcall __noreturn start(__int64 a1, __int64 a2, void (*a3)(void));
FILE **deregister_tm_clones();
__int64 register_tm_clones(void); // weak
FILE **_do_global_dtors_aux();
__int64 frame_dummy(); // weak
void setup();
int win();
__int64 __fastcall compress(_BYTE *a1, int a2, __int64 a3);
__int64 vuln();
int __fastcall main(int argc, const char **argv, const char **envp);
void term_proc();
// int _libc_start_main(int (*main)(int, char **, char **), int argc, char **ubp_av, void (*init)(void), void (*fini)(void), void (*rtld_fini)(void), void *stack_end);
// __int64 _gmon_start__(void); weak

//-------------------------------------------------------------------------
// Data declarations

const char byte_402043 = '\0'; // idb
__int64 (*qword_403FF8)(void) = NULL; // weak
FILE *_bss_start; // idb
FILE *stdin; // idb
char completed_0; // weak


//----- (0000000000401000) ----------------------------------------------------
__int64 (**init_proc())(void)
{
  __int64 (**result)(void); // rax

  result = &_gmon_start__;
  if ( &_gmon_start__ )
    return (__int64 (**)(void))_gmon_start__();
  return result;
}
// 4040A0: using guessed type __int64 _gmon_start__(void);

//----- (0000000000401020) ----------------------------------------------------
__int64 sub_401020()
{
  return qword_403FF8();
}
// 401020: using guessed type __int64 sub_401020();
// 403FF8: using guessed type __int64 (*qword_403FF8)(void);

//----- (0000000000401090) ----------------------------------------------------
// positive sp value has been detected, the output may be wrong!
void __fastcall __noreturn start(__int64 a1, __int64 a2, void (*a3)(void))
{
  __int64 v3; // rax
  int v4; // esi
  __int64 v5; // [rsp-8h] [rbp-8h] BYREF
  char *retaddr; // [rsp+0h] [rbp+0h] BYREF

  v4 = v5;
  v5 = v3;
  _libc_start_main((int (*)(int, char **, char **))main, v4, &retaddr, 0, 0, a3, &v5);
  __halt();
}
// 401096: positive sp value 8 has been found
// 40109D: variable 'v3' is possibly undefined

//----- (00000000004010D0) ----------------------------------------------------
FILE **deregister_tm_clones()
{
  return &_bss_start;
}

//----- (0000000000401100) ----------------------------------------------------
__int64 register_tm_clones()
{
  return 0;
}
// 401100: using guessed type __int64 register_tm_clones();

//----- (0000000000401140) ----------------------------------------------------
FILE **_do_global_dtors_aux()
{
  FILE **result; // rax

  if ( !completed_0 )
  {
    result = deregister_tm_clones();
    completed_0 = 1;
  }
  return result;
}
// 404058: using guessed type char completed_0;

//----- (0000000000401170) ----------------------------------------------------
__int64 frame_dummy()
{
  return register_tm_clones();
}
// 401100: using guessed type __int64 register_tm_clones(void);
// 401170: using guessed type __int64 frame_dummy();

//----- (0000000000401176) ----------------------------------------------------
void setup()
{
  setbuf(stdin, 0);
  setbuf(_bss_start, 0);
}

//----- (00000000004011A5) ----------------------------------------------------
int win()
{
  return system("cat flag.txt");
}

//----- (00000000004011BB) ----------------------------------------------------
__int64 __fastcall compress(_BYTE *a1, int a2, __int64 a3)
{
  _BYTE v4[5]; // [rsp+1Bh] [rbp-Dh]
  unsigned int v5; // [rsp+20h] [rbp-8h]
  int v6; // [rsp+24h] [rbp-4h]

  v4[0] = *a1;
  *(_DWORD *)&v4[1] = 1;
  v6 = 1;
  v5 = 0;
  while ( v6 < a2 )
  {
    while ( *(int *)&v4[1] <= 254 && v6 < a2 && v4[0] == a1[v6] )
    {
      ++*(_DWORD *)&v4[1];
      ++v6;
    }
    *(_BYTE *)(a3 + (int)v5) = v4[0];
    *(_BYTE *)((int)v5 + 1LL + a3) = v4[1];
    v5 += 2;
    v4[4] = 0;
    *(_DWORD *)v4 = (unsigned __int8)a1[v6];
  }
  return v5;
}

//----- (000000000040126B) ----------------------------------------------------
__int64 vuln()
{
  char buf[768]; // [rsp+0h] [rbp-610h] BYREF
  _BYTE v2[772]; // [rsp+300h] [rbp-310h] BYREF
  int v3; // [rsp+604h] [rbp-Ch]
  unsigned int v4; // [rsp+608h] [rbp-8h]
  int i; // [rsp+60Ch] [rbp-4h]

  memset(v2, 0, 0x300u);
  memset(buf, 0, sizeof(buf));
  while ( 1 )
  {
    puts("data to compress : ");
    v4 = read(0, buf, 0x300u);
    if ( !strncmp(buf, "exit", 4u) )
      break;
    v3 = compress(buf, v4, v2);
    printf("compressed data  : ");
    for ( i = 0; i < v3; ++i )
      printf("%02X", (unsigned __int8)v2[i]);
    puts(&byte_402043);
  }
  return 0;
}
// 4011BB: using guessed type __int64 __fastcall compress(_QWORD, _QWORD, _QWORD);

//----- (0000000000401381) ----------------------------------------------------
int __fastcall main(int argc, const char **argv, const char **envp)
{
  setup(argc, argv, envp);
  vuln();
  puts("bye");
  return 0;
}
// 401176: using guessed type __int64 __fastcall setup(_QWORD, _QWORD, _QWORD);
// 40126B: using guessed type __int64 vuln(void);

//----- (00000000004013B0) ----------------------------------------------------
void term_proc()
{
  ;
}

// nfuncs=28 queued=13 decompiled=13 lumina nreq=0 worse=0 better=0
// ALL OK, 13 function(s) have been successfully decompiled
