/* This file was generated by the Hex-Rays decompiler version 9.1.0.250226.
   Copyright (c) 2007-2021 Hex-Rays <info@hex-rays.com>

   Detected compiler: GNU C++
*/

#include <defs.h>


//-------------------------------------------------------------------------
// Function declarations

__int64 (**init_proc())(void);
void sub_401020();
void sub_401030();
void sub_401040();
void sub_401050();
void sub_401060();
void sub_401070();
void sub_401080();
void sub_401090();
void sub_4010A0();
void sub_4010B0();
// int puts(const char *s);
// int printf(const char *format, ...);
// void *memset(void *s, int c, size_t n);
// ssize_t read(int fd, void *buf, size_t nbytes);
// int prctl(int option, ...);
// int setvbuf(FILE *stream, char *buf, int modes, size_t n);
// int mprotect(void *addr, size_t len, int prot);
// void perror(const char *s);
// void __noreturn exit(int status);
void __fastcall __noreturn start(__int64 a1, __int64 a2, void (*a3)(void));
void *sub_401190();
void *sub_401200();
__int64 sub_401230(); // weak
int sub_401236();
int sub_401317();
int sub_401354();
ssize_t sub_4013B9();
signed __int64 sub_4013ED();
__int64 __fastcall main(__int64 a1, char **a2, char **a3);
void term_proc();
// int _libc_start_main(int (*main)(int, char **, char **), int argc, char **ubp_av, void (*init)(void), void (*fini)(void), void (*rtld_fini)(void), void *stack_end);
// __int64 _gmon_start__(void); weak

//-------------------------------------------------------------------------
// Data declarations

_UNKNOWN unk_404060; // weak
_UNKNOWN unk_404070; // weak
FILE *stdout; // idb
FILE *stdin; // idb
FILE *stderr; // idb
char byte_4040A8; // weak


//----- (0000000000401000) ----------------------------------------------------
__int64 (**init_proc())(void)
{
  __int64 (**result)(void); // rax

  result = &_gmon_start__;
  if ( &_gmon_start__ )
    return (__int64 (**)(void))_gmon_start__();
  return result;
}
// 404100: using guessed type __int64 _gmon_start__(void);

//----- (0000000000401020) ----------------------------------------------------
void sub_401020()
{
  JUMPOUT(0);
}
// 401026: control flows out of bounds to 0

//----- (0000000000401030) ----------------------------------------------------
void sub_401030()
{
  sub_401020();
}

//----- (0000000000401040) ----------------------------------------------------
void sub_401040()
{
  sub_401020();
}

//----- (0000000000401050) ----------------------------------------------------
void sub_401050()
{
  sub_401020();
}

//----- (0000000000401060) ----------------------------------------------------
void sub_401060()
{
  sub_401020();
}

//----- (0000000000401070) ----------------------------------------------------
void sub_401070()
{
  sub_401020();
}

//----- (0000000000401080) ----------------------------------------------------
void sub_401080()
{
  sub_401020();
}

//----- (0000000000401090) ----------------------------------------------------
void sub_401090()
{
  sub_401020();
}

//----- (00000000004010A0) ----------------------------------------------------
void sub_4010A0()
{
  sub_401020();
}

//----- (00000000004010B0) ----------------------------------------------------
void sub_4010B0()
{
  sub_401020();
}

//----- (0000000000401150) ----------------------------------------------------
// positive sp value has been detected, the output may be wrong!
void __fastcall __noreturn start(__int64 a1, __int64 a2, void (*a3)(void))
{
  __int64 v3; // rax
  int v4; // esi
  __int64 v5; // [rsp-8h] [rbp-8h] BYREF
  char *retaddr; // [rsp+0h] [rbp+0h] BYREF

  v4 = v5;
  v5 = v3;
  _libc_start_main(main, v4, &retaddr, 0, 0, a3, &v5);
  __halt();
}
// 40115A: positive sp value 8 has been found
// 401161: variable 'v3' is possibly undefined

//----- (0000000000401190) ----------------------------------------------------
void *sub_401190()
{
  return &unk_404070;
}

//----- (0000000000401200) ----------------------------------------------------
void *sub_401200()
{
  void *result; // rax

  if ( !byte_4040A8 )
  {
    result = sub_401190();
    byte_4040A8 = 1;
  }
  return result;
}
// 4040A8: using guessed type char byte_4040A8;

//----- (0000000000401230) ----------------------------------------------------
__int64 sub_401230()
{
  return 0;
}
// 401230: using guessed type __int64 sub_401230();

//----- (0000000000401236) ----------------------------------------------------
int sub_401236()
{
  int result; // eax

  setvbuf(stdin, 0, 2, 0);
  setvbuf(stdout, 0, 2, 0);
  setvbuf(stderr, 0, 2, 0);
  if ( prctl(38, 1, 0, 0, 0) < 0 )
  {
    perror("prctl(PR_SET_NO_NEW_PRIVS)");
    exit(1);
  }
  result = prctl(22, 2, &unk_404060);
  if ( result < 0 )
  {
    perror("prctl(PR_SET_SECCOMP)");
    exit(1);
  }
  return result;
}

//----- (0000000000401317) ----------------------------------------------------
int sub_401317()
{
  puts("You are so lucky!");
  puts("Here is your gift:");
  return mprotect(0, 0x1000u, 1);
}

//----- (0000000000401354) ----------------------------------------------------
int sub_401354()
{
  char s[16]; // [rsp+0h] [rbp-10h] BYREF

  memset(s, 0, sizeof(s));
  puts("Could you tell me your name?");
  read(0, s, 0x18u);
  return printf("Hello, %s!\n", s);
}

//----- (00000000004013B9) ----------------------------------------------------
ssize_t sub_4013B9()
{
  _BYTE buf[96]; // [rsp+0h] [rbp-60h] BYREF

  puts("Any thing else?");
  return read(0, buf, 0x200u);
}

//----- (00000000004013ED) ----------------------------------------------------
signed __int64 sub_4013ED()
{
  puts("Goodbye!");
  return sys_exit(0);
}

//----- (0000000000401413) ----------------------------------------------------
__int64 __fastcall main(__int64 a1, char **a2, char **a3)
{
  sub_401236(a1, a2, a3);
  puts("Welcome");
  sub_401354();
  sub_4013B9();
  sub_4013ED();
  return 0;
}
// 401236: using guessed type __int64 __fastcall sub_401236(_QWORD, _QWORD, _QWORD);
// 401354: using guessed type __int64 sub_401354(void);
// 4013B9: using guessed type __int64 sub_4013B9(void);
// 4013ED: using guessed type __int64 sub_4013ED(void);

//----- (000000000040145C) ----------------------------------------------------
void term_proc()
{
  ;
}

// nfuncs=42 queued=22 decompiled=22 lumina nreq=0 worse=0 better=0
// ALL OK, 22 function(s) have been successfully decompiled
